
project_id = "atthfkcmknkcyfeumcrq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.delete-user-data]
verify_jwt = true

[functions.get-ocr-job]
verify_jwt = false

[functions.ocr-pdf]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.guest-session-sync]
verify_jwt = false

[functions.link-guest-to-user]
verify_jwt = true

[functions.admin-guest-sessions]
verify_jwt = true

[auth.email]
template = "send-auth-email"
